---
- name: Email Test
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Sending notification email
     mail:
       host: smtp.gmail.com
       port: 587
       username: cscsivakumar@gmail.com
       password: Solutions@123
       to: sivakumar_rajendran@condenast.com
       subject: US AWS Ansible-Server build report
       body: Hi Team the server Testmail has been provisioned successfully.
       secure: never
     delegate_to: localhost

     