---
- name: Install Chrome Browser Win_Package#
  #hosts: '{{ target }}'
  hosts: AWXWINRS
  become_user: SYSTEM
  become: True
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ AD_username }}"
    ansible_become_pass: "{{ AD_password }}"
  
  tasks:
   - name: Install Chrome Browser
     win_package:
      path: https://dl.google.com/chrome/install/latest/chrome_installer.exe
      product_id: 'auto'
      arguments:  "/silent /install"